### ISSUE TITLE
关于create

### ISSUE THREAD

**Issue by jesty666** [enenH/pwatch-c#1]
大佬您好    perfMap.create(*(int *) arg, 0x7AF5A7D750这个0x的地址 是填写加密的某者坐标地址吗

**Comment by ajdjcfdn** [comment]
leader_fd = 3
PERF_EVENT_IOC_SET_OUTPUT 11: Success
PERF_EVENT_IOC_SET_OUTPUT: Invalid argument
无效参数怎么解决？

**Comment by ajdjcfdn** [comment]
> leader_fd = 3 PERF_EVENT_IOC_SET_OUTPUT 11： Success PERF_EVENT_IOC_SET_OUTPUT： Invalid argument 无效参数怎么解决？

难道是5.10内核不支持?

**Comment by enenH** [comment]
不好意思，代码发错了
